name: UI Check Workflows

on:
    push:
        paths: 'actions/ui-check/**'
    pull_request:
        paths: 'actions/ui-check/**'

jobs:
    run_tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run sanity checks on ui tests
              run: |
                  npm install
                  npm run test:e2e:sanity
                  npm run test:unit:sanity
              working-directory: actions/ui-check
