name: Test My Theme

on:
  push:
    branches: [ main ] ## Change the branch name to match yours
  pull_request:
    branches: [ main ] ## Change the branch name to match yours


jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Theme Test
      id: test
      uses: Wordpress/theme-review-action@trunk
      with:
        accessible-ready: true
        ui-debug: true

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Screenshots
